# docker-compose.prod.yml

version: '2'

services:
    pweb:
        restart: always

        build:
            context: ../philo-b
            dockerfile: dockerfiles/Dockerfile.production

        # image needs to be specified, or it seems to go for default naming.
        image: prod_web_2
        container_name: pweb

        depends_on:
            - db
        ports:
            - "8004"
        volumes:
            - ../philo-b:/philo-b-docker
            - ../overhead:/overhead
        env_file:
            - ../administration/.env
        environment:
            PRODUCTION: 'true'

        # Is meant for debugging in
        # the terminal via pdb. tty Can
        # introduce a bug 
        # "consider setting COMPOSE_HTTP_TIMEOUT" 
        stdin_open: true
        tty: true

        command: "/overhead/start.sh"

    nginx:
        restart: always
        container_name: nginx_server
        build:
            context: ../nginx
            dockerfile: Dockerfile
        image: nginx_2
        ports:
            - "80:8100"
            - "443:4440"
        volumes:
            - ../nginx/conf/philob.conf:/etc/nginx/conf.d/philob.conf
            - ../philo-b/staticfiles:/var/www/philo-b/static
            - ../philo-b/mediafiles:/var/www/philo-b/media

            - ../philo-b/.well-known:/var/www/philo-b/letsencrypt/wellknown
            - /etc/letsencrypt/live/philo-b.xyz/fullchain.pem:/ssl/cert.pem
            - /etc/letsencrypt/live/philo-b.xyz/privkey.pem:/ssl/key.pem

