version: '2'

services: 

    db:
        restart: always
        image: postgres
        user: postgres:postgres
        ports:
            - "5432"
        volumes:
            - pg_philob:/var/lib/postgresql/data

volumes:
    pg_philob: 
        external: true

