# docker-compose.prod.yml
# made to look like docker-compose.yml

version: '2'

services:

    pweb:
        restart: always

        build:
            context: ../philo-b
            dockerfile: dockerfiles/Dockerfile.production

        # image needs to be specified, or it seems to go for default naming.
        image: prod_web_2
        container_name: pweb

        depends_on:
            - db

        # - not needed icw with networks?
        # - not needed icw sockets?
        ports:
            - "8004"

        volumes:
            - ../philo-b:/philo-b-docker
            - ../overhead:/overhead

        env_file:
            - ../administration/.env

        environment:
            PRODUCTION: 'true'

        # labels:
        #     com.example.service: "web"
        #     com.example.description: "Use for the main web process"

        # networks:
        #     - nginx_network 

        # - this is to get pdb going
        # - but turned of because tty causes the 
        # "consider setting COMPOSE_HTTP_TIMEOUT" bug
        stdin_open: true
        tty: true

        command: "/overhead/start.sh"

    nginx:
        restart: always
        container_name: nginx_server
        build:
            context: ../nginx
            dockerfile: Dockerfile

        image: nginx_2

        ports:
            - "80:81"
            - "443:444"

        # - would be nice to put end with a slash in case of directories
        # - is it possible to just select a file, and refer it to a directory?
        # - use the :ro, as suggested in docker blog for nginx deployment 
        volumes:
            - ../nginx/conf/philob.conf:/etc/nginx/conf.d/philob.conf
            - ../philo-b/philo-b/static:/var/www/philo-b/static
			
            - ../philo-b/.well-known:/var/www/philo-b/letsencrypt/wellknown
            - /etc/letsencrypt/live/philo-b.xyz/fullchain.pem:/ssl/cert.pem
            - /etc/letsencrypt/live/philo-b.xyz/privkey.pem:/ssl/key.pem

