# docker-compose.override.yml

version: '2'

services: 
    web:
        restart: always

        build: 
            context: ../philo-b
            dockerfile: dockerfiles/Dockerfile

        depends_on:
            - db 
        links:
            - db 
        volumes:
            - ../philo-b:/philo-b-docker
            - ../overhead:/overhead
        env_file: 
            - ../administration/.env
        environment:
            PRODUCTION: 'false'
        ports:
            - "8004:8004"

        # Is meant for debugging in
        # the terminal via pdb. tty Can
        # introduce a bug 
        # "consider setting COMPOSE_HTTP_TIMEOUT" 
        # stdin_open: true
        # tty: true

        command: "/overhead/start.sh"

