# docker-compose.yml

version: '2'

services: 

    db:
        restart: always
        image: postgres
        volumes:
            - pg_philob:/var/lib/postgresql/data
        ports:
            - "5432"

volumes:
    pg_philob: 
        external: true
        # - array, ...... string, : mapping

