version: '2'

services:
    pweb:
        restart: always
        # image needs to be specified, or it goes for default naming.
        image: prod_web_2
        container_name: pweb
        build:
            context: ../philo-b
            dockerfile: dockerfiles/Dockerfile.production
        depends_on:
            - db
        ports:
            - "8004"
        volumes:
            - ../philo-b:/philo-b-docker
            - ../overhead:/overhead
        env_file:
            - ../administration/.env
        environment:
            PRODUCTION: 'true'

        # Is meant for debugging in
        # the terminal via pdb. Can
        # introduce the bug:
        # "..consider setting COMPOSE_HTTP_TIMEOUT.."
        # stdin_open: true
        # tty: true

        command: "/overhead/start.sh"

    nginx:
        restart: always
        image: nginx_2
        container_name: nginx_server
        build:
            context: ../nginx
            dockerfile: Dockerfile
        depends_on:
            - pweb
        ports:
            - "80:8100"
            - "443:4440"
        volumes:

            - ../../pelican_ceilings/output:/var/www/pelican_ceilings/output:ro
            # - ../../test_pelican_ceilings/output:/var/www/test_pelican_ceilings/output:ro

            # - ../nginx/conf/46.101.245.22.conf:/etc/nginx/conf.d/46.101.245.22.conf:ro
            - ../nginx/conf/druqtemaker.conf:/etc/nginx/conf.d/druqtemaker.conf:ro
            - ../philo-b/staticfiles:/var/www/philo-b/static:ro
            - ../philo-b/mediafiles:/var/www/philo-b/media:ro

            - ../philo-b/.well-known:/var/www/philo-b/letsencrypt/wellknown:ro

            # - /etc/letsencrypt/live/philo-b.xyz    /fullchain.pem:/ssl/cert.pem:ro
            # - /etc/letsencrypt/live/philo-b.xyz    /privkey.pem:/ssl/key.pem:ro
            - /etc/letsencrypt/live/druqtemaker.com/fullchain.pem:/ssl/cert.pem:ro
            - /etc/letsencrypt/live/druqtemaker.com/privkey.pem:/ssl/key.pem:ro

