# Generated by Django 2.0.5 on 2018-11-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181102_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_last',
            field=models.BooleanField(default=True),
        ),
    ]
