# Generated by Django 2.0.5 on 2018-11-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180917_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='"This is my default message."', verbose_name='Comment'),
        ),
    ]
