# Generated by Django 2.0.5 on 2018-05-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180512_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog_id',
            new_name='post_id',
        ),
    ]
