# Generated by Django 2.0.5 on 2018-05-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180512_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_first',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='is_last',
            field=models.BooleanField(default=True),
        ),
    ]
