# Generated by Django 2.0.5 on 2018-05-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180515_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_first',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_last',
            field=models.NullBooleanField(),
        ),
    ]
